/*
If you use or adapt this software in your research please consult
the author at afonso.goncalves@m-iti.org on how to cite it.

Copyright (C) 2017  Afonso Gonçalves 

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>
 */

using UnityEngine;
using Windows.Kinect;

public class BodySourceViewer : MonoBehaviour
{
    public GameObject _avatar;

    private KinectBodySource _bodySource;
    private KinectSensor _sensor;
    public GameObject[] Avatars { get; private set; }
    public bool[] _activeAvatars;

    void Start()
    {
        _bodySource = gameObject.GetComponent<KinectBodySource>();
    }

    void Update()
    {

        if (_sensor == null)
        {
            _sensor = _bodySource.Sensor;
            if (_sensor == null) return;

            Avatars = new GameObject[_sensor.BodyFrameSource.BodyCount];
            _activeAvatars = new bool[_sensor.BodyFrameSource.BodyCount];
        }

        Body[] kinectBodies = _bodySource.GetData();
        if (kinectBodies == null)
        {
            //Destroy all avatars that exist
            for (int bodyIndex = 0; bodyIndex < _sensor.BodyFrameSource.BodyCount; bodyIndex++)
            {
                if (Avatars[bodyIndex] == null) continue;

                Destroy(Avatars[bodyIndex]);
                Avatars[bodyIndex] = null;
                _activeAvatars[bodyIndex] = false;
            }
            return;
        }

        for (int bodyIndex = 0; bodyIndex < _sensor.BodyFrameSource.BodyCount; bodyIndex++)
        {
            if (kinectBodies[bodyIndex] != null)
            {
                if (!_activeAvatars[bodyIndex] && kinectBodies[bodyIndex].IsTracked)
                {
                    Avatars[bodyIndex] = Instantiate(_avatar);
                    Avatars[bodyIndex].transform.SetParent(gameObject.transform);
                    Avatars[bodyIndex].GetComponent<JointPositionControl>().SetBodyIndex(bodyIndex);
                    Avatars[bodyIndex].GetComponent<JointOrientationControl>().SetBodyIndex(bodyIndex);
                    _activeAvatars[bodyIndex] = true;
                }
                else if (_activeAvatars[bodyIndex] && !kinectBodies[bodyIndex].IsTracked)
                {
                    //Destroy the avatar if it exists but the corresponding body is not being tracked
                    Destroy(Avatars[bodyIndex]);
                    Avatars[bodyIndex] = null;
                    _activeAvatars[bodyIndex] = false;
                }
            }
            else
            {
                //Destroy the avatar if the body is null
                Destroy(Avatars[bodyIndex]);
                Avatars[bodyIndex] = null;
                _activeAvatars[bodyIndex] = false;
            }
        }
    }
}
